# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your
# code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
---
pr:
  branches:
    exclude:
      - gh-pages
    include:
      - '*'

trigger:
  branches:
    exclude:
      - gh-pages
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    steps:
      - script: npm install
        displayName: 'Install dependencies'
      - script: npm run build
        displayName: 'Build styleguide'

  - job: Lint
    steps:
      - script: npm run lint
        displayName: 'Lint JS'

  - job: Test
    steps:
      - script: npm run test:all-with-coverage
        displayName: 'Run unit tests'

  - job: Publish Styleguide
    steps:
      - script: npm run publish:styleguide
        displayName: 'Publish styleguide to gh-pages'
        env:
          GIT_BRANCH: $(Build.SourceBranchName)
          GIT_BRANCH_PR: $(System.PullRequest.SourceBranch)
          GITHUB_ACCESS_TOKEN: $(github.accessToken)
          GITHUB_OWNER: octopusthink
          GITHUB_REPO: nautilus
          GITHUB_USER: mechanical-octopus
