# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your
# code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
---
pr:
  branches:
    exclude:
      - gh-pages
    include:
      - '*'

trigger:
  branches:
    exclude:
      - gh-pages
    include:
      - master

jobs:
  - job: lint
    displayName: Lint
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: npm install
        displayName: 'Install dependencies'
      - script: npm run lint:eslint
        displayName: 'Lint JS'
      # Removed because stylelint isn't playing super-well with emotion.
      # It helps flag some things but errors on composition when it really
      # shouldn't. It'd be great to enable this eventually though...
      # - script: npm run lint:stylelint
      #   displayName: 'Lint CSS'
