---
pr:
  branches:
    exclude:
      - '*'

trigger:
  branches:
    exclude:
      - gh-pages
    include:
      - master

jobs:
  - job: publish_styleguide
    displayName: Publish Styleguide
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: npm install
        displayName: 'Install dependencies'
      - script: npm run publish:styleguide
        displayName: 'Publish styleguide to gh-pages'
        env:
          GITHUB_ACCESS_TOKEN: $(github.accessToken)
          GITHUB_OWNER: octopusthink
          GITHUB_REPO: nautilus
          GITHUB_USER: mechanical-octopus
