---
pr:
  branches:
    exclude:
      - '*'

trigger:
  branches:
    exclude:
      - '*'
  tags:
    include:
      - v*

jobs:
  - job: publish_styleguide
    displayName: Publish Styleguide
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: npm install
        displayName: 'Install dependencies'
      - script: npm run publish:styleguide-for-version
        displayName: 'Publish styleguide to gh-pages for this release'
        env:
          GITHUB_ACCESS_TOKEN: $(github.accessToken)
          GITHUB_OWNER: octopusthink
          GITHUB_REPO: nautilus
          GITHUB_USER: mechanical-octopus
  - job: publish_to_npm
    displayName: Publish package to NPM
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: npm install
        displayName: 'Install dependencies'
      - script: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        displayName: 'Set NPM Auth Token'
      - script: npm publish
        displayName: 'Publish release'
        env:
          NPM_TOKEN: $(npm.accessToken)
