---
pr:
  branches:
    exclude:
      - gh-pages
    include:
      - '*'

trigger:
  branches:
    exclude:
      - gh-pages
    include:
      - master

jobs:
  - job: test
    displayName: Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: npm install
        displayName: 'Install dependencies'
      - script: npm run test:all-with-coverage
        displayName: 'Run unit tests'
