---
name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        run: npm install
      - name: Lint JS
        run: npm run lint:eslint
      # Removed because stylelint isn't playing super-well with emotion.
      # It helps flag some things but errors on composition when it really
      # shouldn't. It'd be great to enable this eventually though...
      # - name: Lint CSS
      #   run: npm run lint:css
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        run: npm install
      - name: Run unit tests and code coverage
        run: npm run test:all-with-coverage
