---
name: Publish Styleguide

on: push

push:
  branches:
    - master

jobs:
  styleguide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        run: npm install
      # - name: Publish to gh-pages
      #   run: npm run publish:styleguide
      #   env:
      #     GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      #     GITHUB_OWNER: octopusthink
      #     GITHUB_REPO: nautilus
      #     GITHUB_USER: mechanical-octopus
